add_test( DataStructuresTest.DeviceDefaultValues /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=DataStructuresTest.DeviceDefaultValues]==] --gtest_also_run_disabled_tests)
set_tests_properties( DataStructuresTest.DeviceDefaultValues PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( DataStructuresTest.DeviceWithValues /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=DataStructuresTest.DeviceWithValues]==] --gtest_also_run_disabled_tests)
set_tests_properties( DataStructuresTest.DeviceWithValues PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( DataStructuresTest.ServiceTypeDefaultValues /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=DataStructuresTest.ServiceTypeDefaultValues]==] --gtest_also_run_disabled_tests)
set_tests_properties( DataStructuresTest.ServiceTypeDefaultValues PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( DataStructuresTest.ServiceTypeWithValues /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=DataStructuresTest.ServiceTypeWithValues]==] --gtest_also_run_disabled_tests)
set_tests_properties( DataStructuresTest.ServiceTypeWithValues PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( DataStructuresTest.ServiceRecordDefaultValues /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=DataStructuresTest.ServiceRecordDefaultValues]==] --gtest_also_run_disabled_tests)
set_tests_properties( DataStructuresTest.ServiceRecordDefaultValues PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( DataStructuresTest.ServiceRecordWithValues /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=DataStructuresTest.ServiceRecordWithValues]==] --gtest_also_run_disabled_tests)
set_tests_properties( DataStructuresTest.ServiceRecordWithValues PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ConfigTest.ConfigFileExists /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=ConfigTest.ConfigFileExists]==] --gtest_also_run_disabled_tests)
set_tests_properties( ConfigTest.ConfigFileExists PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ConfigTest.ConfigFileParsable /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=ConfigTest.ConfigFileParsable]==] --gtest_also_run_disabled_tests)
set_tests_properties( ConfigTest.ConfigFileParsable PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BoundaryTest.EmptyStrings /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=BoundaryTest.EmptyStrings]==] --gtest_also_run_disabled_tests)
set_tests_properties( BoundaryTest.EmptyStrings PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BoundaryTest.LongStrings /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=BoundaryTest.LongStrings]==] --gtest_also_run_disabled_tests)
set_tests_properties( BoundaryTest.LongStrings PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BoundaryTest.ZeroAndNegativeValues /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=BoundaryTest.ZeroAndNegativeValues]==] --gtest_also_run_disabled_tests)
set_tests_properties( BoundaryTest.ZeroAndNegativeValues PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BoundaryTest.LargeCostValues /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=BoundaryTest.LargeCostValues]==] --gtest_also_run_disabled_tests)
set_tests_properties( BoundaryTest.LargeCostValues PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UnicodeTest.CyrillicStrings /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=UnicodeTest.CyrillicStrings]==] --gtest_also_run_disabled_tests)
set_tests_properties( UnicodeTest.CyrillicStrings PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UnicodeTest.CyrillicInServiceType /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=UnicodeTest.CyrillicInServiceType]==] --gtest_also_run_disabled_tests)
set_tests_properties( UnicodeTest.CyrillicInServiceType PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( StatusTest.DeviceStatusValues /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=StatusTest.DeviceStatusValues]==] --gtest_also_run_disabled_tests)
set_tests_properties( StatusTest.DeviceStatusValues PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( VectorTest.DeviceVector /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=VectorTest.DeviceVector]==] --gtest_also_run_disabled_tests)
set_tests_properties( VectorTest.DeviceVector PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( VectorTest.ServiceTypeVector /home/adminstd/gitpr/build_tests/test_simple [==[--gtest_filter=VectorTest.ServiceTypeVector]==] --gtest_also_run_disabled_tests)
set_tests_properties( VectorTest.ServiceTypeVector PROPERTIES WORKING_DIRECTORY /home/adminstd/gitpr/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( test_simple_TESTS DataStructuresTest.DeviceDefaultValues DataStructuresTest.DeviceWithValues DataStructuresTest.ServiceTypeDefaultValues DataStructuresTest.ServiceTypeWithValues DataStructuresTest.ServiceRecordDefaultValues DataStructuresTest.ServiceRecordWithValues ConfigTest.ConfigFileExists ConfigTest.ConfigFileParsable BoundaryTest.EmptyStrings BoundaryTest.LongStrings BoundaryTest.ZeroAndNegativeValues BoundaryTest.LargeCostValues UnicodeTest.CyrillicStrings UnicodeTest.CyrillicInServiceType StatusTest.DeviceStatusValues VectorTest.DeviceVector VectorTest.ServiceTypeVector)
